import 'package:equatable/equatable.dart';
import 'package:flutter/cupertino.dart';

// TODO immutable was not generated by plug-in. why not?
@immutable
abstract class PillBoxSetEvent extends Equatable {
  // TODO plugin generated the following line. why?
  // const PillBoxSetEvent();
  @override
  List<Object> get props => [];
}

class GetPillBoxSet extends PillBoxSetEvent {
  final String dependent;

  GetPillBoxSet({@required this.dependent});
}
