// Mocks generated by Mockito 5.0.0 from annotations
// in pusherman/test/features/schedule/data/repositories/caretaker_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i7;

import 'package:http/src/client.dart' as _i4;
import 'package:http/src/response.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pusherman/core/network/network_info.dart' as _i6;
import 'package:pusherman/features/schedule/data/datasources/caretaker_local_data_source.dart'
    as _i8;
import 'package:pusherman/features/schedule/data/datasources/caretaker_remote_data_source.dart'
    as _i9;
import 'package:pusherman/features/schedule/data/models/caretaker_model.dart'
    as _i3;
import 'package:shared_preferences/shared_preferences.dart' as _i2;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

class _FakeSharedPreferences extends _i1.Fake implements _i2.SharedPreferences {
}

class _FakeCaretakerModel extends _i1.Fake implements _i3.CaretakerModel {}

class _FakeClient extends _i1.Fake implements _i4.Client {}

class _FakeResponse extends _i1.Fake implements _i5.Response {}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i6.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<bool> get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected),
          returnValue: Future.value(false)) as _i7.Future<bool>);
}

/// A class which mocks [CaretakerLocalDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockCaretakerLocalDataSourceImpl extends _i1.Mock
    implements _i8.CaretakerLocalDataSourceImpl {
  MockCaretakerLocalDataSourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SharedPreferences get sharedPreferences =>
      (super.noSuchMethod(Invocation.getter(#sharedPreferences),
          returnValue: _FakeSharedPreferences()) as _i2.SharedPreferences);
  @override
  _i7.Future<_i3.CaretakerModel> get(String? name) =>
      (super.noSuchMethod(Invocation.method(#get, [name]),
              returnValue: Future.value(_FakeCaretakerModel()))
          as _i7.Future<_i3.CaretakerModel>);
  @override
  _i7.Future<void> put(_i3.CaretakerModel? model) =>
      (super.noSuchMethod(Invocation.method(#put, [model]),
          returnValue: Future.value(null),
          returnValueForMissingStub: Future.value()) as _i7.Future<void>);
}

/// A class which mocks [CaretakerRemoteDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockCaretakerRemoteDataSourceImpl extends _i1.Mock
    implements _i9.CaretakerRemoteDataSourceImpl {
  MockCaretakerRemoteDataSourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Client get client => (super.noSuchMethod(Invocation.getter(#client),
      returnValue: _FakeClient()) as _i4.Client);
  @override
  _i7.Future<_i3.CaretakerModel> get(String? caretaker) =>
      (super.noSuchMethod(Invocation.method(#get, [caretaker]),
              returnValue: Future.value(_FakeCaretakerModel()))
          as _i7.Future<_i3.CaretakerModel>);
  @override
  _i7.Future<_i5.Response> put(_i3.CaretakerModel? caretaker) =>
      (super.noSuchMethod(Invocation.method(#put, [caretaker]),
              returnValue: Future.value(_FakeResponse()))
          as _i7.Future<_i5.Response>);
}
